project_type=OLD
stationName=ar095
storeFile=/home/jenkins/agent/workspace/AR095-Pages-india-yaarwin/capacitor/android/assets/cert/key1.jks
storePassword=123456
keyAlias=key1
keyPassword=123456
type=android
applicationId=com.YaarWin.app
appName=YaarWin
packageAddress=https://yaarwin0.com
versionCode=2
versionName=2.0.0
packageType=native
domainUrl=https://yaarwin0.com
icon=https:/pack.arwebplus.com/ar095/icon.png
launcher=https:/pack.arwebplus.com/ar095/launcher.png