###### Class com.YaarWin.app.R is created by jadx
###### Class com.YaarWin.app.R.anim is created by jadx
###### Class com.YaarWin.app.R.animator is created by jadx
###### Class com.YaarWin.app.R.array is created by jadx
###### Class com.YaarWin.app.R.attr is created by jadx
###### Class com.YaarWin.app.R.bool is created by jadx
###### Class com.YaarWin.app.R.color is created by jadx
###### Class com.YaarWin.app.R.dimen is created by jadx
###### Class com.YaarWin.app.R.drawable is created by jadx
###### Class com.YaarWin.app.R.id is created by jadx
###### Class com.YaarWin.app.R.integer is created by jadx
###### Class com.YaarWin.app.R.interpolator is created by jadx
###### Class com.YaarWin.app.R.layout is created by jadx
###### Class com.YaarWin.app.R.mipmap is created by jadx
###### Class com.YaarWin.app.R.raw is created by jadx
###### Class com.YaarWin.app.R.string is created by jadx
###### Class com.YaarWin.app.R.style is created by jadx
###### Class com.YaarWin.app.R.xml is created by jadx